name: tsvetomir_stanev_employees
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  path_provider: ^2.0.14
  csv: ^5.0.1
  file_picker: ^4.0.0
  permission_handler: ^8.1.4
  intl: ^0.18.0
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5

dev_dependencies:
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
